### PR TITLE
Add emits property

### PR DESCRIPTION
**Pull request by raineorshine**
In Vue v3, components should contain an `emits` property that lists all custom events. `ckeditor5-vue` now prints a warning to the console every time an event is emitted.

```
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop. 
  at <Ckeditor editor=fn<Rb> modelValue="<p>Hello</p>" onUpdate:modelValue=fn  ... > 
  at <Content name="email-invite-user" class="editor" > 
  at <Invite onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {$iam: ƒ, $dateFormat: ƒ, …} > > 
  at <RouterView> 
  at <App>
```

This PR fixes this and makes the warning go away.

**Reference:**
https://v3.vuejs.org/guide/component-custom-events.html#validate-emitted-events

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
@raineorshine Thank you for submitting this pull request!

I thought I was going mad. Kept thinking I was missing something with all the console warnings when using this with Vue 3. I hope it gets merged soon.

@pomek How do you feel about this PR? Any thoughts?

Thank you!

https://v3.vuejs.org/guide/migration/emits-option.html#_3-x-behavior

**Comment by raineorshine** [comment]
Any update on getting this merged? 🙂

*nudge*

**Comment by psmyrek** [comment]
I am not able to reproduce it on my side using Vue v3.1.5.
Could you please give us more details on how you use the component?
Which version of Vue do you use?

**Comment by raineorshine** [comment]
I was on Vue `v3.0.5`. Seems to be working on `"vue": "^3.1.5"` and `"@ckeditor/ckeditor5-vue": "^2.0.1"`!

**Pull request closed without merging**
