### PR TITLE
T/51: Used `config.initialData` instead of `innerHTML` to set the initial state of the editor

### LINKED ISSUE #51: Change way of setting data
A follow-up to https://github.com/ckeditor/ckeditor5-vue/issues/47.

We shouldn't use the `el.innerHTML` unless it's necessary, because it can easily provide some attack vectors and is slow for large contents. We should use the [`initialValue` property](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData) instead.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Used `config.initialData` instead of `innerHTML` to set the initial state of the editor. Closes #51.

---

### Additional information

Nuke the `node_modules` before running tests. The newer build-classic is required to support `initialData`.

### CODE REVIEW

**Comment by ma2ciek** [comment]
I see that now there're such warnings on CI:

```
ERROR: '[vue-test-utils]: Global error handler detected (Vue.config.errorHandler). 
Vue Test Utils sets a custom error handler to throw errors thrown by instances. If you want this behavior in your tests, you must remove the global error handler.'
```

Are they correct?

**Comment by oleq** [comment]
They are incorrect. Or not very accurate. Because tests use `Vue.nextTick`, things are asynchronous and `done()` is used in places like this https://github.com/ckeditor/ckeditor5-vue/blob/t/51/tests/ckeditor.js#L50 in the past.

I added `Vue.config.errorHandler = done;` in all tests as recommended in the [official guide](https://vue-test-utils.vuejs.org/guides/#getting-started) to improve readability of errors.

 Before:
image

After:
image

It helps a lot but for some reason, vue-tests-utils displays an error (which kinda contradicts their documentation...). Maybe this is because vue-tests-utils is still beta (?). Anyway, it's not changing anything but DX so we can either remove the `Vue.config.errorHandler = done;` line and live with ugly Mocha errors or just live with quirky errors from vue-tests-utils.

**Comment by oleq** [comment]
What about the PR itself? Does it make sense?

**Comment by ma2ciek** [comment]
Overall the PR is good and the change makes sense, I'm merging it.

**Pull request merged**
