### PR TITLE
Vue 3.x support

### LINKED ISSUE #158: Vue 3 Support
Now Vue 3 has been released, do you know when you'll support it?

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: `CKEditor` component supports Vue 3.x. Closes #158.

BREAKING CHANGE: The `CKEditor` component no longer supports Vue 2.x.

---

As mentioned in [official migration guide](https://v3.vuejs.org/guide/migration/render-function-api.html#overview), the `render` function in Vue 3.x no longer receives the `h` function (which is a conventional alias for `createElement`) as an argument, so in Vue 3.x `h` has to be globally imported. Due to that fact, Vue has been [externalized in webpack configuration](https://v3.vuejs.org/guide/migration/render-function-api.html#library-authors).

### CODE REVIEW

**Comment by oleq** [comment]
Will this check introduced in [4f44fc2](https://github.com/ckeditor/ckeditor5-vue/pull/165/commits/4f44fc28bfd244c23fa2eaf694b639a0bceda595) work when Vue.js and the component are loaded via [direct script include](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#direct-script-include)? It looks like it will only work while the component is being built by webpack.

**Comment by psmyrek** [comment]
> 
> 
> Will this check introduced in [4f44fc2](https://github.com/ckeditor/ckeditor5-vue/pull/165/commits/4f44fc28bfd244c23fa2eaf694b639a0bceda595) work when Vue.js and the component are loaded via [direct script include](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#direct-script-include)? It looks like it will only work while the component is being built by webpack.

Yes, it will work via direct script include. I've confirmed that by replacing the script tag for Vue in `sample/index.html`, where the editor is loaded via `<script src="../dist/ckeditor.js"></script>`:

```html
<!-- <script src="../node_modules/vue/dist/vue.global.js"></script> -->
<!-- Let's check unsupported Vue version... -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js"></script>
<script src="../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js"></script>
<script src="../dist/ckeditor.js"></script>
```

and then nice red exception is logged in the console.

**Comment by psmyrek** [comment]
Code coverage dropped by 4.4% due to lack of test for this recently added Vue version check. No idea how to stub Vue version here... 🤔

**Comment by pomek** [comment]
As we have no idea how to stub the Vue version in tests, let's ignore this if while checking the code coverage.

**Pull request merged**
