### PR TITLE
`v7.1.0` release

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Changelog for `v7.1.0`.

### CODE REVIEW

**Comment by Mati365** [comment]
@pomek Should we include changelog from alpha?

**Comment by pomek** [comment]
> @pomek Should we include changelog from alpha?

I would say yes because we want to show the difference between minor versions. Alpha is not considered stable, so users can ignore it.

**Comment by Mati365** [comment]
I'll adjust changelog then

**Review by Witoso — DISMISSED** [review]

**Review by pomek — APPROVED** [review]

**Comment by pomek** [comment]
Once the PR is merged, please ping @psmyrek / @martnpaneq to process the publishing process.

**Pull request merged**
